from .base import BaseAgent
import random
import uuid
import logging
from datetime import datetime, timedelta

logger = logging.getLogger("FundraiserActor")

class FundraiserActor(BaseAgent):
    def __init__(self, name: str, create_campaign_probability: float = 0.01):
        super().__init__(name, agent_type="fundraiser")
        self.create_campaign_probability = create_campaign_probability
        self.owned_campaigns = []

    async def act(self, sim_state):
        """Randomly decide to create or manage a campaign."""
        # Check if it's time to create a new campaign
        if random.random() < self.create_campaign_probability:
            await self.create_campaign(sim_state)

        # Basic management logic for existing campaigns
        for campaign_id in self.owned_campaigns:
            campaign = sim_state.campaigns.get(campaign_id)
            if not campaign:
                continue
            
            # Simple state machine to progress the campaign through its lifecycle
            if campaign['status'] == 'draft':
                # Randomly 'submit' the campaign after some time in draft
                if random.random() < 0.1:
                    campaign['status'] = 'pending_review'
                    logger.info(f"Campaign {campaign['title']} ({campaign_id[:8]}) submitted by {self.name}")

            elif campaign['status'] == 'active':
                # Check for funding completion
                if campaign['total_contributions'] >= campaign['funding_goal']:
                    campaign['status'] = 'funded'
                    logger.info(f"Campaign {campaign['title']} ({campaign_id[:8]}) is now FULLY FUNDED")

    async def create_campaign(self, sim_state):
        campaign_id = str(uuid.uuid4())
        goal = random.choice([5000, 10000, 25000, 50000])
        
        campaign = {
            "campaign_id": campaign_id,
            "title": f"Simulated Campaign by {self.name} #{len(self.owned_campaigns)+1}",
            "description": "A campaign automatically generated by the simulation engine.",
            "funding_goal": goal,
            "total_contributions": 0.0,
            "status": "active", # Start active for simpler initial simulation
            "created_at": sim_state.current_time,
            "fundraiser_id": self.id
        }
        
        sim_state.campaigns[campaign_id] = campaign
        self.owned_campaigns.append(campaign_id)
        
        logger.info(f"Fundraiser {self.name} created campaign: {campaign['title']} (Goal: {goal})")
        
        sim_state.events.append({
            "type": "campaign_created",
            "agent_id": self.id,
            "agent_name": self.name,
            "campaign_id": campaign_id,
            "goal": goal,
            "timestamp": sim_state.current_time
        })
