"""Update transaction_ledger with FKs and enum

Revision ID: 144923b245ea
Revises: cd081b7aadba
Create Date: 2025-11-30 22:29:04.378813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144923b245ea'
down_revision = 'cd081b7aadba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    transaction_type_enum = sa.Enum('contribution', 'disbursement', 'refund', name='transaction_type')
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('transaction_ledger', sa.Column('contribution_id', sa.UUID(), nullable=True))
    op.add_column('transaction_ledger', sa.Column('fund_release_id', sa.UUID(), nullable=True))
    op.add_column('transaction_ledger', sa.Column('refund_event_id', sa.UUID(), nullable=True))
    
    # Convert existing data if any (set to NULL or a default value)
    # Then alter the column type
    op.execute("ALTER TABLE transaction_ledger ALTER COLUMN transaction_type TYPE transaction_type USING transaction_type::transaction_type")
    
    op.create_foreign_key(None, 'transaction_ledger', 'fund_release', ['fund_release_id'], ['release_id'])
    op.create_foreign_key(None, 'transaction_ledger', 'contribution', ['contribution_id'], ['contribution_id'])
    op.create_foreign_key(None, 'transaction_ledger', 'refund_event', ['refund_event_id'], ['refund_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_ledger', type_='foreignkey')
    op.drop_constraint(None, 'transaction_ledger', type_='foreignkey')
    op.drop_constraint(None, 'transaction_ledger', type_='foreignkey')
    op.alter_column('transaction_ledger', 'transaction_type',
               existing_type=sa.Enum('contribution', 'disbursement', 'refund', name='transaction_type'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('transaction_ledger', 'refund_event_id')
    op.drop_column('transaction_ledger', 'fund_release_id')
    op.drop_column('transaction_ledger', 'contribution_id')
    # ### end Alembic commands ###
