"""make_uname_and_phone_unique

Revision ID: 21422f70c50f
Revises: 6168493e13bf
Create Date: 2026-02-27 21:34:55.262016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21422f70c50f'
down_revision = '6168493e13bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contributor_profile_phone_number'), 'contributor_profile', ['phone_number'], unique=True)
    op.create_index(op.f('ix_contributor_profile_uname'), 'contributor_profile', ['uname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributor_profile_uname'), table_name='contributor_profile')
    op.drop_index(op.f('ix_contributor_profile_phone_number'), table_name='contributor_profile')
    # ### end Alembic commands ###
