"""Add media columns

Revision ID: 2823fc436764
Revises: 21422f70c50f
Create Date: 2026-03-05 16:44:59.494108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2823fc436764'
down_revision = '21422f70c50f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('cover_image_url', sa.String(length=255), nullable=True))
    op.add_column('milestone_evidence', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone_evidence', 'description')
    op.drop_column('campaign', 'cover_image_url')
    # ### end Alembic commands ###
