"""add_fcm_token_to_account

Revision ID: 643405aba481
Revises: ab58aada546a
Create Date: 2026-03-20 15:58:53.931656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643405aba481'
down_revision = 'ab58aada546a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'fcm_token')
    # ### end Alembic commands ###
