"""Add refund_event table

Revision ID: 6a4ecb7086ac
Revises: c074c67ea47a
Create Date: 2025-11-30 13:38:57.688996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4ecb7086ac'
down_revision = 'c074c67ea47a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_event',
    sa.Column('refund_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('amount_refunded', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('refund_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_event')
    # ### end Alembic commands ###
