"""Add campaign_rating table

Revision ID: 6cc4424f20fd
Revises: 6a4ecb7086ac
Create Date: 2025-11-30 13:42:44.746281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc4424f20fd'
down_revision = '6a4ecb7086ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_rating',
    sa.Column('campaign_rating_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating_value >= 1 AND rating_value <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('campaign_rating_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_rating')
    # ### end Alembic commands ###
