"""Add fundraiser_campaign_history table

Revision ID: 6d50f01096ba
Revises: 6cc4424f20fd
Create Date: 2025-11-30 13:50:28.192354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d50f01096ba'
down_revision = '6cc4424f20fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundraiser_campaign_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('fundraiser_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('is_high_budget', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser_profile.fundraiser_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundraiser_campaign_history')
    # ### end Alembic commands ###
