"""Add is_waived to vote_submission

Revision ID: 92a43bf1d355
Revises: 144923b245ea
Create Date: 2025-11-30 23:03:36.008975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a43bf1d355'
down_revision = '144923b245ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_submission', sa.Column('is_waived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_submission', 'is_waived')
    # ### end Alembic commands ###
