"""expand_pipeline_tracking_and_last_login

Revision ID: a267db1942ee
Revises: dcf2a4ac663c
Create Date: 2026-02-07 09:54:37.539101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a267db1942ee"
down_revision = "dcf2a4ac663c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS fundraiser_campaign_history CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_history CASCADE")
    
    op.add_column("account", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.add_column("account", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("submitted_for_review_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("approved_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("launched_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("funded_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("phases_started_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("failed_at", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("current_milestone_number", sa.Integer(), nullable=True))
    op.add_column("campaign", sa.Column("milestones_approved_count", sa.Integer(), nullable=True))
    op.add_column("campaign", sa.Column("milestones_rejected_count", sa.Integer(), nullable=True))
    op.drop_column("campaign", "remedial_reserve_rm")
    
    # SMART MIGRATION FOR milestone_number
    op.add_column("milestone", sa.Column("milestone_number", sa.Integer(), nullable=True))
    op.execute("UPDATE milestone SET milestone_number = phase_index")
    op.execute("UPDATE milestone SET milestone_number = 1 WHERE milestone_number IS NULL")
    op.alter_column("milestone", "milestone_number", nullable=False)

    op.add_column("milestone", sa.Column("activated_at", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("evidence_submitted_at", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("voting_start_date", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("voting_end_date", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("approved_at", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("rejected_at", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("funds_released_at", sa.DateTime(), nullable=True))
    op.add_column("milestone", sa.Column("revision_count", sa.Integer(), nullable=True))
    op.add_column("milestone", sa.Column("max_revisions", sa.Integer(), nullable=True))
    
    op.drop_column("milestone", "vote_window_start")
    op.drop_column("milestone", "deadline")
    op.drop_column("milestone", "phase_index")
    op.drop_column("milestone", "vote_window_end")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
