"""add_budget_data_to_campaign

Revision ID: ab58aada546a
Revises: 2823fc436764
Create Date: 2026-03-20 12:56:32.587575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab58aada546a'
down_revision = '2823fc436764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('budget_data', sa.Text(), nullable=True))
    op.drop_column('vote_submission', 'dissent_settled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_submission', sa.Column('dissent_settled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'budget_data')
    # ### end Alembic commands ###
