"""Add fund_release table

Revision ID: c074c67ea47a
Revises: e894d327aa36
Create Date: 2025-11-30 13:28:41.675479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c074c67ea47a'
down_revision = 'e894d327aa36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_release',
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('amount_released', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.milestone_id'], ),
    sa.PrimaryKeyConstraint('release_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_release')
    # ### end Alembic commands ###
