"""Add description to milestone

Revision ID: c2214454b426
Revises: 6d50f01096ba
Create Date: 2025-11-30 18:08:43.396578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2214454b426'
down_revision = '6d50f01096ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'description')
    # ### end Alembic commands ###
