"""Add signature and unique constraint to vote_submission

Revision ID: cd081b7aadba
Revises: d0c3f066e440
Create Date: 2025-11-30 20:59:09.414635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd081b7aadba'
down_revision = 'd0c3f066e440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_submission', sa.Column('signature', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_vote_milestone_contributor', 'vote_submission', ['milestone_id', 'contributor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vote_milestone_contributor', 'vote_submission', type_='unique')
    op.drop_column('vote_submission', 'signature')
    # ### end Alembic commands ###
