"""Initial migration

Revision ID: e894d327aa36
Revises: 
Create Date: 2025-11-28 19:53:43.213301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e894d327aa36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'contributor', 'fundraiser', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('company_category_l1',
    sa.Column('l1_id', sa.UUID(), nullable=False),
    sa.Column('l1_name', sa.String(length=100), nullable=True),
    sa.Column('l1_risk_weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('l1_id')
    )
    op.create_table('company_risk_mapping',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('l1_weight', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('l2_weight', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('default_l2_adjust', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('min_risk', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('max_risk', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('company_category_l2',
    sa.Column('l2_id', sa.UUID(), nullable=False),
    sa.Column('l1_id', sa.UUID(), nullable=True),
    sa.Column('l2_name', sa.String(length=100), nullable=True),
    sa.Column('l2_risk_weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['l1_id'], ['company_category_l1.l1_id'], ),
    sa.PrimaryKeyConstraint('l2_id')
    )
    op.create_table('contributor_profile',
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('uname', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('contributor_id')
    )
    op.create_table('fundraiser_profile',
    sa.Column('fundraiser_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('br_number', sa.String(length=50), nullable=True),
    sa.Column('industry_l1_id', sa.UUID(), nullable=True),
    sa.Column('industry_l2_id', sa.UUID(), nullable=True),
    sa.Column('risk_score_c', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('br_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['industry_l1_id'], ['company_category_l1.l1_id'], ),
    sa.ForeignKeyConstraint(['industry_l2_id'], ['company_category_l2.l2_id'], ),
    sa.PrimaryKeyConstraint('fundraiser_id')
    )
    op.create_table('campaign',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('fundraiser_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('funding_goal_f', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duration_d', sa.Integer(), nullable=True),
    sa.Column('campaign_type_ct', sa.Enum('donation', name='campaign_type'), nullable=True),
    sa.Column('funding_start_date', sa.DateTime(), nullable=True),
    sa.Column('funding_end_date', sa.DateTime(), nullable=True),
    sa.Column('category_c', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('num_phases_p', sa.Integer(), nullable=True),
    sa.Column('alpha_value', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('remedial_reserve_rm', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('total_contributions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_released', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'funded', 'in_phases', 'completed', 'failed', name='campaign_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser_profile.fundraiser_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('campaign_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('total_raised', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_released', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('was_fully_funded', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('contribution',
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='contribution_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('escrow_account',
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('total_contributions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_released', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('escrow_id')
    )
    op.create_table('milestone',
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('phase_index', sa.Integer(), nullable=True),
    sa.Column('phase_weight_wi', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('disbursement_percentage_di', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('release_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vote_window_start', sa.DateTime(), nullable=True),
    sa.Column('vote_window_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'released', name='milestone_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_table('vote_token',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('transaction_ledger',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_account.escrow_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('vote_result',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('total_yes', sa.Integer(), nullable=True),
    sa.Column('total_no', sa.Integer(), nullable=True),
    sa.Column('quorum', sa.Integer(), nullable=True),
    sa.Column('yes_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outcome', sa.Enum('approved', 'rejected', name='vote_outcome'), nullable=True),
    sa.Column('tallied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.milestone_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('vote_submission',
    sa.Column('vote_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('vote_hash', sa.Text(), nullable=True),
    sa.Column('vote_value', sa.Enum('yes', 'no', name='vote_value'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.milestone_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_submission')
    op.drop_table('vote_result')
    op.drop_table('transaction_ledger')
    op.drop_table('vote_token')
    op.drop_table('milestone')
    op.drop_table('escrow_account')
    op.drop_table('contribution')
    op.drop_table('campaign_history')
    op.drop_table('campaign')
    op.drop_table('fundraiser_profile')
    op.drop_table('contributor_profile')
    op.drop_table('company_category_l2')
    op.drop_table('company_risk_mapping')
    op.drop_table('company_category_l1')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
